/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2206 from the
 * contents of Furl.xs. Do not edit this file, edit Furl.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "xs-src/Furl.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#include "xshelper.h"
#include "ppport.h"
#include <curl/curl.h>
#include <curl/easy.h>
#include <string.h>

STATIC_INLINE
size_t furl_content_write(char *ptr, size_t size, size_t nmemb, void*stream) {
    SV*buf = (SV*)stream;
    sv_catpvn(buf, ptr, size*nmemb);
    return size*nmemb;
}

STATIC_INLINE
size_t furl_header_write(char *ptr, size_t size, size_t nmemb, void*stream) {
    AV*buf = (AV*)stream;
    av_push(buf, newSVpv(ptr, size*nmemb));
    return size*nmemb;
}

#line 34 "xs-src/Furl.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 86 "xs-src/Furl.c"

XS(XS_Furl__new_curl); /* prototype to pass -Wmissing-prototypes */
XS(XS_Furl__new_curl)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "agent, timeout");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	const char *	agent = (const char *)SvPV_nolen(ST(0));
	int	timeout = (int)SvIV(ST(1));
#line 32 "xs-src/Furl.xs"
    CURL * curl = curl_easy_init();
    curl_easy_setopt( curl, CURLOPT_USERAGENT,      agent );
    curl_easy_setopt( curl, CURLOPT_TIMEOUT,        timeout );
    curl_easy_setopt( curl, CURLOPT_HEADER,         0 );
    curl_easy_setopt( curl, CURLOPT_NOPROGRESS,     1 );
    curl_easy_setopt( curl, CURLOPT_WRITEFUNCTION,  furl_content_write );
    curl_easy_setopt( curl, CURLOPT_HEADERFUNCTION, furl_header_write );
    XPUSHs(sv_2mortal(newSViv((int)curl)));
    XSRETURN(1);
#line 113 "xs-src/Furl.c"
	PUTBACK;
	return;
    }
}


XS(XS_Furl__request); /* prototype to pass -Wmissing-prototypes */
XS(XS_Furl__request)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 6)
       croak_xs_usage(cv,  "curl_sv, url, headers, method, content, tmpfile");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	curl_sv = ST(0);
	const char *	url = (const char *)SvPV_nolen(ST(1));
	SV*	headers = ST(2);
	const char *	method = (const char *)SvPV_nolen(ST(3));
	const char *	content = (const char *)SvPV_nolen(ST(4));
	SV*	tmpfile = ST(5);
#line 45 "xs-src/Furl.xs"
    CURL * curl = (CURL*)SvIV(curl_sv);
    curl_easy_setopt( curl, CURLOPT_URL,        url );
    curl_easy_setopt( curl, CURLOPT_POSTFIELDS, content );
    curl_easy_setopt( curl, CURLOPT_CUSTOMREQUEST, method );
    struct curl_slist *header_slist = NULL;
    {
        AV *array = (AV *)SvRV(headers);
        int last = av_len(array);
        int i;

        for (i=0;i<=last;i++) {
            SV **sv = av_fetch(array,i,0);
            STRLEN len = 0;
            char *string = SvPV(*sv, len);
            if (len == 0) break;
            header_slist = curl_slist_append(header_slist, string);
        }
        header_slist = curl_slist_append(header_slist, "\015\012");

        curl_easy_setopt(curl, CURLOPT_HTTPHEADER, header_slist);

    }
    SV* res_content = sv_2mortal(newSVpv("", 0));
    curl_easy_setopt(curl, CURLOPT_WRITEDATA, res_content);

    AV* res_headers = newAV();
    curl_easy_setopt(curl, CURLOPT_HEADERDATA, res_headers);

    CURLcode retcode = curl_easy_perform(curl);

    curl_slist_free_all(header_slist);
    EXTEND(SP, 3);
    if (retcode == 0) {
        long status;
        if (CURLE_OK != curl_easy_getinfo(curl, CURLINFO_HTTP_CODE, &status)) {
            croak("FATAL");
        }
        PUSHs(sv_2mortal(newSViv(status)));
        PUSHs(sv_2mortal(newRV((SV*)res_headers)));
        PUSHs(res_content);
    } else {
        PUSHs(sv_2mortal(newSViv(500)));
        PUSHs(sv_2mortal(newRV((SV*)res_headers)));
        const char * errstr = curl_easy_strerror(retcode);
        PUSHs(sv_2mortal(newSVpvn(errstr, strlen(errstr))));
    }
    XSRETURN(3);
#line 187 "xs-src/Furl.c"
	PUTBACK;
	return;
    }
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Furl); /* prototype to pass -Wmissing-prototypes */
XS(boot_Furl)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXS("Furl::_new_curl", XS_Furl__new_curl, file);
        newXS("Furl::_request", XS_Furl__request, file);

    /* Initialisation Section */

#line 27 "xs-src/Furl.xs"
    curl_global_init(0);

#line 222 "xs-src/Furl.c"

    /* End of Initialisation Section */

#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

